name: Build and Re-seal Flutter APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        cache: true


    - name: Set up Java JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'adoptopenjdk'
        java-version: '17'

    - name: Cache Dart packages
      uses: actions/cache@v3
      with:
        path: /home/runner/.pub-cache
        key: ${{ runner.os }}-dart-${{ hashFiles('**/pubspec.yaml') }}
        restore-keys: |
          ${{ runner.os }}-dart-

    - name: Get dependencies
      run: flutter pub get

    - name: Build APK
      run: flutter build apk --release --split-per-abi

    - name: Upload APKs as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: flutter-apks
        path: ./build/app/outputs/flutter-apk/