name: Android Release
on:
  push:
    branches: [ "master" ]
  workflow_dispatch:
jobs:
  
  build:
    name: Build Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "21.x" 
          cache: 'gradle' 
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.4"
          channel: 'stable'
          cache: true
      # 12
      - name: Get dependencies
        run: flutter pub get
      - name: Flutter Runner
        run: flutter build apk --release --split-per-abi
      - name: Push to Release
        uses: ncipollo/release-action@v1
        with:
          artifacts : "build/app/outputs/apk/debug/*"
          tag : "v1.0.0"
          token: ${{ secrets.TOKEN  }}
          name : "Release v1.0.0"
          allowUpdates : true
